### PR TITLE
Support markdown 3.7, fix AttributeError: module 'markdown' has no attribute 'version_info'

### PR DESCRIPTION
**Pull request by themanyone**
This not only stops the errors, but actually works this time!  

- Supports markdown 3.7
- Inserts ~~strikethru~~
- Inserts <del&gt; element into HTML preview like it's supposed to.

I tried also making it work with markdown 2.0 because the code tests for it but...

- Enki wasn't working with Markdown 2.0 BEFORE this PR.

Easiest way to prove it:
```
git checkout f32dc18e
python setup.py install
python -m enki
.micromamba/envs/enki_md2/lib/python3.7/site-packages/docutils-0.21.2-py3.7.egg/docutils/utils/math/latex2mathml.py", line 311, in <module>
    'dbinom': layout_styles['displaystyle'] | {'linethickness': 0},
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```
According to https://github.com/run-llama/llama_index/issues/10101 this TypeErrror is due to the use of the "|" operator to merge dictionaries. This feature was introduced in Python 3.9, so was is not available for Python 3.7.

- [at least] Python 3.9 is required to run Enki
- Python 3.7 is the last version to support markdown 2.0
- Hence, markdown 2.0 has not been working for some time.

### CODE REVIEW

**Comment by rapgro** [comment]
Replaces #486 .

**Comment by opsec-ai** [comment]
28            DEL_RE = r'(~~)(.*?)~~'  # Simplified regex pattern is unused. Line can be deleted, np
